[package]
name = "rusty-keybase-bot"
version = "0.1.0"
authors = ["Marco Munizaga <marco@marcopolo.io>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
rusty-keybase-protocol = { path = "../rusty-keybase-protocol" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-preview = "0.3.0-alpha.18"